### ISSUE TITLE
Problem running ReadFiles

### ISSUE THREAD

**Issue by basilesportif** [rusiaaman/wcgw#19]
I keep getting the following whenever running ReadFiles, so it keeps falling back to BashCommand:

```
{
  "file_paths": [
    "/Users/blah/Documents/Notes/TODO.md"
  ],
  "type": "text"
}
Result
[
  {
    "type": "text",
    "text": "the JSON object must be str, bytes or bytearray, not list"
  }
]
```

**Comment by rusiaaman** [comment]
Unfortunately, I am unable to replicate the issue.

Could you ensure that the json you shared is correct?

```{
  "file_paths": [
    "/Users/blah/Documents/Notes/TODO.md"
  ],
  "type": "text"
}```

Is this exactly what claude requested? The following is a snapshot from my system.

<img width="522" alt="image" src="https://github.com/user-attachments/assets/cd838b2c-f3f0-437f-9526-ebbc6c896a65" />


The error is very weird. Is it a one-off issue or are you facing it in all conversations?

**Comment by rusiaaman** [comment]
Are you using claude using mcp or is the error from some other flow?

**Comment by basilesportif** [comment]
It's in LibreChat, using MCP. It works in Claude's desktop app, in the manner you show.

Weirdly, `BashCommand` and `FileEdit` work just fine, which is why I posted here and not in their repo. If it's their issue, I can raise it there.

**Comment by rusiaaman** [comment]
The issue seems to be LibreChat not respecting `const` keyword in the tools' JSON schema. 

Anyway I have removed the relevant code as it was unnecessary, so this is now working in LibreChat.

**Comment by basilesportif** [comment]
Works now! You're the man.
