### ISSUE TITLE
Could not connect to MCP server mgcw

### ISSUE THREAD

**Issue by ichoosetoaccept** [rusiaaman/wcgw#8]
Hi

My claude_desktop_config.json:
```
{
    "mcpServers": {
        "memory": {
            "command": "npx",
            "args": ["-y", "@modelcontextprotocol/server-memory"]
        },
        "wcgw": {
            "command": "uv",
            "args": [
                "tool",
                "run",
                "--from",
                "wcgw@latest",
                "--python",
                "3.12",
                "wcgw_mcp",
                "--computer-use"
            ]
        }
    }
}
```

When I start Claude for Desktop (macOS) I see this:
![CleanShot 2024-12-07 at 19 57 48@2x](https://github.com/user-attachments/assets/fdc5cee2-ea88-43d8-b188-35c505dfb62d)

This also happens without computer-use.

I have [Orbstack](https://orbstack.dev/) installed and running (for Docker).

Any idea what might be going wrong in my setup?

Thanks!

**Comment by WalshJake818** [comment]
I don't know about Claude with computer-use since I haven't tried it, but it works for me when using the full path from 'which uv'

**Comment by ichoosetoaccept** [comment]
Ok that did the trick, thank you!
README.md should be updated to mention this.

**Comment by waveozhangli** [comment]
> I don't know about Claude with computer-use since I haven't tried it, but it works for me when using the full path from 'which uv'

I got the same problem, thank you very much!
